services:
  - type: web
    name: shopee-scraper
    env: python
    runtime: python-3.11.9
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
